// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-west-2',
  aws_cognito_identity_pool_id:
    'us-west-2:e690e849-758d-41c4-91ac-fe1d08cd6dd3',
  aws_cognito_region: 'us-west-2',
  aws_user_pools_id: 'us-west-2_vdK4usBQe',
  aws_user_pools_web_client_id: '17s9fcn6n7dtqkn4mqn7r7ll17',
  oauth: {},
  aws_appsync_graphqlEndpoint:
    'https://komp7cojcjcilj4gjwa5ozy7fq.appsync-api.us-west-2.amazonaws.com/graphql',
  aws_appsync_region: 'us-west-2',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS'
};

export default awsmobile;
